services:
  - type: web
    name: cataract-detection
    env: python
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cataract_db
          property: connectionString

  - type: redis
    name: cataraqt-redis
    ipAllowList: []
    plan: free

databases:
  - name: cataract_db
    plan: free
