services:
  - type: web
    name: cataract-detection
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements-render.txt --prefer-binary
    startCommand: gunicorn app:app
    plan: free
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.12
      - key: PORT
        value: 10000
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: cataract_db
          property: connectionString
      - key: PIP_EXTRA_INDEX_URL
        value: https://download.pytorch.org/whl/cpu

  - type: redis
    name: cataraqt-redis
    ipAllowList: []
    plan: free

databases:
  - name: cataract_db
    plan: free
